[package]
name = "sample"
version = "0.1.0"
authors = ["Song Li <songl@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xml-rs = "0.8"
reqwest = "0.10"
tokio = { version = "0.2", features = ["full"] }
